# Dados CensitÃ¡rios

## Fontes de Dados

In [1]:
%matplotlib inline
import pandas as pd
import geopandas as gpd

In [8]:
#!conda install -c rmg xlrd -y

Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::notebook==6.0.3=py38_0
  - defaults/noarch::nltk==3.5=py_0
  - defaults/noarch::jupyter_client==6.1.6=py_0
  - defaults/noarch::dask==2.20.0=py_0
  - defaults/linux-64::distributed==2.20.0=py38_0
  - defaults/noarch::anaconda-project==0.8.4=py_0
  - defaults/linux-64::matplotlib==3.2.2=0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/linux-64::jupyter==1.0.0=py38_7
  - defaults/linux-64::bkcharts==0.2=py38_0
  - defaults/noarch::nbformat==5.0.7=py_0
  - defaults/linux-64::jsonschema==3.2.0=py38_0
  - defaults/linux-64::conda-build==3.18.11=py38_0
  - defaults/noarch::ipywidgets==7.5.1=py_0
  - defaults/noarch::sphinx==3.1.2=py_0
  - defaults/noarch::jupyterlab==2.1.5=py_0
  - defaults/linux-64::anaconda-client==1.7.2=py38_0
  - defaults/noarch::jupyterlab_server==1.2.0=py_0
  - defaults/linux-64::spyder==4.1.4=py38_0
  - defaults/linux-64::pandas==1.0.5=py38h0573a6f_0
  - defaults/linux-64::scikit-image==0.16.2=py38h0573a6f_0
  - defaults/linux-64::widgetsnbextension==3.5.1=py38_0
  - defaults/noarch::qtconsole==4.7.5=py_0
  - defaults/linux-64::pytest==5.4.3=py38_0
  - defaults/linux-64::anaconda-navigator==1.9.12=py38_0
  - defaults/linux-64::anaconda==2020.07=py38_0
  - conda-forge/noarch::jupyterthemes==0.20.0=py_1
  - defaults/noarch::numpydoc==1.1.0=py_0
  - defaults/noarch::jupyter_console==6.1.0=py_0
  - defaults/linux-64::spyder-kernels==1.9.2=py38_0
  - defaults/linux-64::ipykernel==5.3.2=py38h5ca1d4c_0
  - defaults/linux-64::matplotlib-base==3.2.2=py38hef1b27d_0
  - defaults/linux-64::nbconvert==5.6.1=py38_0
  - defaults/linux-64::bokeh==2.1.1=py38_0
  - defaults/noarch::seaborn==0.10.1=py_0
  - defaults/noarch::bleach==3.1.5=py_0
  - defaults/linux-64::_ipyw_jlab_nb_ext_conf==0.1.0=py38_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::notebook==6.0.3=py38_0
  - defaults/noarch::nltk==3.5=py_0
  - defaults/noarch::jupyter_client==6.1.6=py_0
  - defaults/noarch::dask==2.20.0=py_0
  - defaults/linux-64::distributed==2.20.0=py38_0
  - defaults/noarch::anaconda-project==0.8.4=py_0
  - defaults/linux-64::matplotlib==3.2.2=0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/linux-64::jupyter==1.0.0=py38_7
  - defaults/linux-64::bkcharts==0.2=py38_0
  - defaults/noarch::nbformat==5.0.7=py_0
  - defaults/linux-64::jsonschema==3.2.0=py38_0
  - defaults/linux-64::conda-build==3.18.11=py38_0
  - defaults/noarch::ipywidgets==7.5.1=py_0
  - defaults/noarch::sphinx==3.1.2=py_0
  - defaults/noarch::jupyterlab==2.1.5=py_0
  - defaults/linux-64::anaconda-client==1.7.2=py38_0
  - defaults/noarch::jupyterlab_server==1.2.0=py_0
  - defaults/linux-64::spyder==4.1.4=py38_0
  - defaults/linux-64::pandas==1.0.5=py38h0573a6f_0
  - defaults/linux-64::scikit-image==0.16.2=py38h0573a6f_0
  - defaults/linux-64::widgetsnbextension==3.5.1=py38_0
  - defaults/noarch::qtconsole==4.7.5=py_0
  - defaults/linux-64::pytest==5.4.3=py38_0
  - defaults/linux-64::anaconda-navigator==1.9.12=py38_0
  - defaults/linux-64::anaconda==2020.07=py38_0
  - conda-forge/noarch::jupyterthemes==0.20.0=py_1
  - defaults/noarch::numpydoc==1.1.0=py_0
  - defaults/noarch::jupyter_console==6.1.0=py_0
  - defaults/linux-64::spyder-kernels==1.9.2=py38_0
  - defaults/linux-64::ipykernel==5.3.2=py38h5ca1d4c_0
  - defaults/linux-64::matplotlib-base==3.2.2=py38hef1b27d_0
  - defaults/linux-64::nbconvert==5.6.1=py38_0
  - defaults/linux-64::bokeh==2.1.1=py38_0
  - defaults/noarch::seaborn==0.10.1=py_0
  - defaults/noarch::bleach==3.1.5=py_0
  - defaults/linux-64::_ipyw_jlab_nb_ext_conf==0.1.0=py38_0
done

## Package Plan ##

  environment location: /home/yorinori/anaconda3

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2020.07  |           py38_0           6 KB
    anaconda-custom            |           py38_1          35 KB
    babel-2.11.0               |   py38h06a4308_0         6.8 MB
    beautifulsoup4-4.11.1      |   py38h06a4308_0         185 KB
    ca-certificates-2020.6.20  |       hecda079_0         145 KB  rmg
    certifi-2020.6.20          |   py38h32f6830_0         151 KB  rmg
    click-8.0.4                |   py38h06a4308_0         151 KB
    conda-22.9.0               |   py38h06a4308_0         884 KB
    conda-build-3.23.3         |   py38h06a4308_0         575 KB
    dataclasses-0.8            |     pyh6d0b6a4_7           8 KB
    flask-1.1.2                |     pyhd3eb1b0_0          70 KB
    html5lib-1.1               |     pyhd3eb1b0_0          91 KB
    itsdangerous-2.0.1         |     pyhd3eb1b0_0          18 KB
    markupsafe-2.0.1           |   py38h27cfd23_0          22 KB
    openssl-1.1.1g             |       h516909a_0         2.1 MB  rmg
    packaging-22.0             |   py38h06a4308_0          68 KB
    patch-2.7.6                |    h7b6447c_1001         119 KB
    patsy-0.5.2                |   py38h06a4308_1         276 KB
    pyrsistent-0.18.0          |   py38heee7806_0          94 KB
    python-dateutil-2.8.2      |     pyhd3eb1b0_0         233 KB
    pytz-2022.7                |   py38h06a4308_0         209 KB
    sqlalchemy-1.4.32          |   py38h7f8727e_0         1.9 MB
    werkzeug-2.0.3             |     pyhd3eb1b0_0         221 KB
    xlrd-2.0.1                 |     pyhd3eb1b0_0          90 KB
    ------------------------------------------------------------
                                           Total:        14.4 MB

The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/linux-64::_anaconda_depends-2020.07-py38_0
  babel              pkgs/main/linux-64::babel-2.11.0-py38h06a4308_0
  beautifulsoup4     pkgs/main/linux-64::beautifulsoup4-4.11.1-py38h06a4308_0
  click              pkgs/main/linux-64::click-8.0.4-py38h06a4308_0
  dataclasses        pkgs/main/noarch::dataclasses-0.8-pyh6d0b6a4_7
  flask              pkgs/main/noarch::flask-1.1.2-pyhd3eb1b0_0
  html5lib           pkgs/main/noarch::html5lib-1.1-pyhd3eb1b0_0
  itsdangerous       pkgs/main/noarch::itsdangerous-2.0.1-pyhd3eb1b0_0
  jinja2             pkgs/main/noarch::jinja2-2.11.3-pyhd3eb1b0_0
  markupsafe         pkgs/main/linux-64::markupsafe-2.0.1-py38h27cfd23_0
  packaging          pkgs/main/linux-64::packaging-22.0-py38h06a4308_0
  patch              pkgs/main/linux-64::patch-2.7.6-h7b6447c_1001
  patsy              pkgs/main/linux-64::patsy-0.5.2-py38h06a4308_1
  pyrsistent         pkgs/main/linux-64::pyrsistent-0.18.0-py38heee7806_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0
  pytz               pkgs/main/linux-64::pytz-2022.7-py38h06a4308_0
  sqlalchemy         pkgs/main/linux-64::sqlalchemy-1.4.32-py38h7f8727e_0
  statsmodels        pkgs/main/linux-64::statsmodels-0.11.1-py38h7b6447c_0
  werkzeug           pkgs/main/noarch::werkzeug-2.0.3-pyhd3eb1b0_0

The following packages will be UPDATED:

  conda              conda-forge::conda-4.10.1-py38h578d9b~ --> pkgs/main::conda-22.9.0-py38h06a4308_0
  conda-build                                3.18.11-py38_0 --> 3.23.3-py38h06a4308_0
  xlrd                                           1.2.0-py_0 --> 2.0.1-pyhd3eb1b0_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2020.6.24-0 --> rmg::ca-certificates-2020.6.20-hecda079_0
  certifi               pkgs/main::certifi-2020.6.20-py38_0 --> rmg::certifi-2020.6.20-py38h32f6830_0
  openssl              pkgs/main::openssl-1.1.1g-h7b6447c_0 --> rmg::openssl-1.1.1g-h516909a_0

The following packages will be DOWNGRADED:

  anaconda                                   2020.07-py38_0 --> custom-py38_1



Downloading and Extracting Packages
dataclasses-0.8      | 8 KB      | ##################################### | 100%
conda-22.9.0         | 884 KB    | ##################################### | 100%
patsy-0.5.2          | 276 KB    | ##################################### | 100%
click-8.0.4          | 151 KB    | ##################################### | 100%
patch-2.7.6          | 119 KB    | ##################################### | 100%
ca-certificates-2020 | 145 KB    | ##################################### | 100%
flask-1.1.2          | 70 KB     | ##################################### | 100%
conda-build-3.23.3   | 575 KB    | ##################################### | 100%
certifi-2020.6.20    | 151 KB    | ##################################### | 100%
_anaconda_depends-20 | 6 KB      | ##################################### | 100%
itsdangerous-2.0.1   | 18 KB     | ##################################### | 100%
pytz-2022.7          | 209 KB    | ##################################### | 100%
xlrd-2.0.1           | 90 KB     | ##################################### | 100%
anaconda-custom      | 35 KB     | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
markupsafe-2.0.1     | 22 KB     | ##################################### | 100%
packaging-22.0       | 68 KB     | ##################################### | 100%
sqlalchemy-1.4.32    | 1.9 MB    | ##################################### | 100%
beautifulsoup4-4.11. | 185 KB    | ##################################### | 100%
html5lib-1.1         | 91 KB     | ##################################### | 100%
python-dateutil-2.8. | 233 KB    | ##################################### | 100%
werkzeug-2.0.3       | 221 KB    | ##################################### | 100%
pyrsistent-0.18.0    | 94 KB     | ##################################### | 100%
babel-2.11.0         | 6.8 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [2]:
censo = pd.read_excel('./data/censo2010/RJ/EXCEL/Basico_RJ.xls')

In [6]:
setor = gpd.read_file('./data/Mapas/RJ-SETOR.shp')

In [7]:
censo.head()

,Cod_setor,Cod_Grandes RegiÃµes,Nome_Grande_Regiao,Cod_UF,Nome_da_UF,Cod_meso,Nome_da_meso,Cod_micro,Nome_da_micro,Cod_RM,...,V003,V004,V005,V006,V007,V008,V009,V010,V011,V012
0,330010005000001,3,RegiÃ£o Sudeste,RJ,Rio de Janeiro,3305,Sul Fluminense,33013,BaÃ­a da Ilha Grande,0,...,2.62,1.94,2356.80,5716056.06,2571.06,5684616.94,1565.37,4344465.56,2192.65,4711305.89
1,330010005000002,3,RegiÃ£o Sudeste,RJ,Rio de Janeiro,3305,Sul Fluminense,33013,BaÃ­a da Ilha Grande,0,...,2.51,1.50,2040.47,3020377.79,2236.67,2869054.77,1816.69,20052928.88,2375.67,24942113.99
2,330010005000003,3,RegiÃ£o Sudeste,RJ,Rio de Janeiro,3305,Sul Fluminense,33013,BaÃ­a da Ilha Grande,0,...,3.08,2.19,2687.80,8362007.52,2836.66,8402987.99,1593.37,7250920.66,2294.84,8835722.10
3,330010005000004,3,RegiÃ£o Sudeste,RJ,Rio de Janeiro,3305,Sul Fluminense,33013,BaÃ­a da Ilha Grande,0,...,3.04,3.25,3026.67,24807309.86,3352.62,26410753.99,1865.52,10994097.59,2574.41,13362652.63
4,330010005000005,3,RegiÃ£o Sudeste,RJ,Rio de Janeiro,3305,Sul Fluminense,33013,BaÃ­a da Ilha Grande,0,...,3.34,1.94,1124.82,712447.24,1229.19,649944.69,689.40,583588.50,1028.21,521878.03

In [8]:
setor.head()

,ID1,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODD,NM_DISTRIT,CD_GEOCODS,NM_SUBDIST,CD_GEOCODM,NM_MUNICIP,NM_MESO,NM_MICRO,geometry
0,408203,330455705300140,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,RIO DE JANEIRO,METROPOLITANA DO RIO DE JANEIRO,RIO DE JANEIRO,"POLYGON ((667.016 7474.986, 667.043 7475.005, ..."
1,408204,330455705300141,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,RIO DE JANEIRO,METROPOLITANA DO RIO DE JANEIRO,RIO DE JANEIRO,"POLYGON ((667.363 7475.226, 667.340 7475.194, ..."
2,408205,330455705300142,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,RIO DE JANEIRO,METROPOLITANA DO RIO DE JANEIRO,RIO DE JANEIRO,"POLYGON ((667.305 7475.856, 667.299 7475.873, ..."
3,408198,330455705300135,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,RIO DE JANEIRO,METROPOLITANA DO RIO DE JANEIRO,RIO DE JANEIRO,"MULTIPOLYGON (((666.791 7475.488, 666.791 7475..."
4,408199,330455705300136,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,RIO DE JANEIRO,METROPOLITANA DO RIO DE JANEIRO,RIO DE JANEIRO,"POLYGON ((666.751 7475.226, 666.793 7475.255, ..."

In [9]:
censo.dtypes

Cod_setor                int64
Cod_Grandes RegiÃµes      int64
Nome_Grande_Regiao      object
Cod_UF                  object
Nome_da_UF              object
Cod_meso                 int64
Nome_da_meso            object
Cod_micro                int64
Nome_da_micro           object
Cod_RM                   int64
Nome_da_RM              object
Cod_municipio            int64
Nome_do_municipio       object
Cod_distrito             int64
Nome_do_distrito        object
Cod_subdistrito          int64
Nome_do_subdistrito     object
Cod_bairro               int64
Nome_do_bairro          object
Situacao_setor           int64
Tipo_setor               int64
V001                   float64
V002                   float64
V003                   float64
V004                   float64
V005                   float64
V006                   float64
V007                   float64
V008                   float64
V009                   float64
V010                   float64
V011                   float64
V012                   float64
dtype: object

In [10]:
setor.dtypes

ID1              int64
CD_GEOCODI      object
TIPO            object
CD_GEOCODB      object
NM_BAIRRO       object
CD_GEOCODD      object
NM_DISTRIT      object
CD_GEOCODS      object
NM_SUBDIST      object
CD_GEOCODM      object
NM_MUNICIP      object
NM_MESO         object
NM_MICRO        object
geometry      geometry
dtype: object

In [11]:
censo['Cod_setor'] = censo['Cod_setor'].astype(str)

In [15]:
censo.dtypes

Cod_setor               object
Cod_Grandes RegiÃµes      int64
Nome_Grande_Regiao      object
Cod_UF                  object
Nome_da_UF              object
Cod_meso                 int64
Nome_da_meso            object
Cod_micro                int64
Nome_da_micro           object
Cod_RM                   int64
Nome_da_RM              object
Cod_municipio            int64
Nome_do_municipio       object
Cod_distrito             int64
Nome_do_distrito        object
Cod_subdistrito          int64
Nome_do_subdistrito     object
Cod_bairro               int64
Nome_do_bairro          object
Situacao_setor           int64
Tipo_setor               int64
V001                   float64
V002                   float64
V003                   float64
V004                   float64
V005                   float64
V006                   float64
V007                   float64
V008                   float64
V009                   float64
V010                   float64
V011                   float64
V012                   float64
dtype: object

In [14]:
type(censo['Cod_setor'].iloc[0])

str

In [16]:
print(type(censo))
print(type(setor))

<class 'pandas.core.frame.DataFrame'>
<class 'geopandas.geodataframe.GeoDataFrame'>

In [17]:
setor.shape

(10504, 14)

In [18]:
setor = pd.merge(setor, censo, left_on='CD_GEOCODI', right_on='Cod_setor', how='left')

In [20]:
setor.shape

(10504, 47)

In [21]:
setor

,ID1,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODD,NM_DISTRIT,CD_GEOCODS,NM_SUBDIST,CD_GEOCODM,...,V003,V004,V005,V006,V007,V008,V009,V010,V011,V012
0,408203,330455705300140,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,...,2.88,2.44,865.00,853496.00,1000.39,851626.14,539.62,577184.79,879.99,642059.29
1,408204,330455705300141,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,...,3.04,2.25,746.23,400714.52,856.36,365433.86,489.76,319508.08,776.84,283719.10
2,408205,330455705300142,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,...,3.13,2.38,873.25,599998.55,987.60,565496.46,574.79,577333.14,883.40,614759.44
3,408198,330455705300135,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,...,3.33,2.43,546.45,268682.25,701.42,235688.46,382.13,205907.30,642.09,178882.45
4,408199,330455705300136,URBANO,330455705140,Costa Barros,330455705,RIO DE JANEIRO,330455705,PAVUNA,3304557,...,3.23,2.37,530.38,173914.73,692.98,114118.18,345.61,155947.84,657.36,91425.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10499,410671,330455705310240,URBANO,330455705142,Guaratiba,330455705,RIO DE JANEIRO,330455705,GUARATIBA,3304557,...,3.67,3.85,1149.14,785889.11,1297.42,693426.02,605.47,586039.11,1116.17,509653.65
10500,410672,330455705310241,URBANO,330455705142,Guaratiba,330455705,RIO DE JANEIRO,330455705,GUARATIBA,3304557,...,3.42,2.29,870.29,240071.86,959.55,178251.94,514.99,268142.31,888.88,129521.98
10501,410673,330455705310242,URBANO,330455705142,Guaratiba,330455705,RIO DE JANEIRO,330455705,GUARATIBA,3304557,...,3.28,2.36,901.30,1096450.73,1025.08,1120250.27,545.51,634154.49,889.08,728301.71
10502,410674,330455705310243,URBANO,330455705142,Guaratiba,330455705,RIO DE JANEIRO,330455705,GUARATIBA,3304557,...,3.27,2.61,819.88,877378.56,964.57,892711.30,484.73,490658.06,813.16,556172.37
10503,410680,330455705310249,URBANO,330455705142,Guaratiba,330455705,RIO DE JANEIRO,330455705,GUARATIBA,3304557,...,3.07,1.49,2012.55,2802763.78,2105.53,2736253.53,1119.69,2173447.69,1735.51,2300311.22

In [22]:
setor.columns

Index(['ID1', 'CD_GEOCODI', 'TIPO', 'CD_GEOCODB', 'NM_BAIRRO', 'CD_GEOCODD',
       'NM_DISTRIT', 'CD_GEOCODS', 'NM_SUBDIST', 'CD_GEOCODM', 'NM_MUNICIP',
       'NM_MESO', 'NM_MICRO', 'geometry', 'Cod_setor', 'Cod_Grandes RegiÃµes',
       'Nome_Grande_Regiao', 'Cod_UF', 'Nome_da_UF ', 'Cod_meso',
       'Nome_da_meso', 'Cod_micro', 'Nome_da_micro', 'Cod_RM', 'Nome_da_RM',
       'Cod_municipio', 'Nome_do_municipio', 'Cod_distrito',
       'Nome_do_distrito', 'Cod_subdistrito', 'Nome_do_subdistrito',
       'Cod_bairro', 'Nome_do_bairro', 'Situacao_setor', 'Tipo_setor', 'V001',
       'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V009', 'V010',
       'V011', 'V012'],
      dtype='object')

In [23]:
type(setor)

geopandas.geodataframe.GeoDataFrame

In [24]:
setor.crs

<Derived Projected CRS: PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_Unk ...>
Name: unknown
Axis Info [cartesian]:
- [east]: Easting (kilometre)
- [north]: Northing (kilometre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Transverse Mercator
Datum: D_Unknown_based_on_GRS80_ellipsoid
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [25]:
setor = setor.to_crs('+proj=utm +zone=23 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=km +no_defs')

In [26]:
setor.crs

<Bound CRS: +proj=utm + zone=23 + south +ellps=GRS80 +towgs84= ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (kilometre)
- N[north]: Northing (kilometre)
Area of Use:
- undefined
Coordinate Operation:
- name: Transformation from unknown to WGS84
- method: Position Vector transformation (geog2D domain)
Datum: Unknown based on GRS80 ellipsoid
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
Source CRS: unknown

In [27]:
setor.to_file('./data/Mapas/RJ-SETOR.shp')

/home/yorinori/anaconda3/lib/python3.8/site-packages/geopandas/io/file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
<ipython-input-27-fc47d2bc618a>:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  setor.to_file('./data/Mapas/RJ-SETOR.shp')